# Testing this workflow is possible using https://github.com/nektos/act
# Act only steps are specified by `if: ${{ env.ACT }}`

name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install yarn
        if: ${{ env.ACT }}
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn bootstrap
      - name: Unit Test
        run: yarn test:ci
  release:
    name: Release
    runs-on: macos-10.15
    needs: test
    if: github.ref == 'refs/heads/master'
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install yarn
        if: ${{ env.ACT }}
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn bootstrap
      - name: Setup Git
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Versions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn lerna version --yes
      - name: Publish NPM Packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          yarn lerna publish from-package --yes
      - name: Write Github Release
        env:
          GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn gh-release --yes
        # In the case no changes to version were made
        continue-on-error: true
      - name: Build MacOS Application
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn media build
          yarn media release
