name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: macos-11.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.4
      - name: Install dependencies
        run: yarn bootstrap
      - name: Unit Test
        run: yarn workspaces run ci
  release:
    name: Release
    runs-on: macos-11.0
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy
        run: echo "Deploying"
